### ISSUE TITLE
100 percent cpu usage

### ISSUE THREAD

**Issue by MyShoesHaveSplinters** [Banabyte/pterodactyl-radio-streaming#1]
program runs at 100 percent cpu usage when i install the program to the panel and install it on my panel

**Comment by ZEROPOINTBRUH** [comment]
I know i havnt documented this yet but have you added any music files in the autodj folder?

**Comment by MyShoesHaveSplinters** [comment]
it is a problem with the software

**Comment by ZEROPOINTBRUH** [comment]
that dosn't awnser my question. did you add any audio files in the autodj folder then restart the service.

**Comment by MyShoesHaveSplinters** [comment]
🙏 thank you so much friend, my problem is fixed.
